### ISSUE TITLE
Validate Should Detect Incorrect NDArray DType

### ISSUE THREAD

**Issue by PaulHuwe** [spacetelescope/roman_datamodels#27]
Validate should detect when the dtype of an ndarray object  does not match the dtype specified in the schema.

**Comment by eslavich** [comment]
Do you have a failing example?  I tested dtype validation and saw the expected error:

```python
import numpy as np
from roman_datamodels.datamodels import FlatRefModel
from roman_datamodels.testing import factories

flat_ref = factories.create_flat_ref(data=np.zeros((4096, 4096), dtype=np.uint64))
Flat = FlatRefModel(flat_ref)
```
```
ValidationError: Can not safely cast from 'uint64' to 'float32'

Failed validating 'datatype' in schema['properties']['data']:
    {'datatype': 'float32',
     'ndim': 2,
     'tag': 'tag:stsci.edu:asdf/core/ndarray-1.0.0',
     'title': 'Flat data array'}

On instance['data']:
    {'byteorder': 'little',
     'datatype': 'uint64',
     'shape': [4096, 4096],
     'source': 0}
```

**Comment by eslavich** [comment]
@PaulHuwe and I discussed this on Slack, the problem lies with dtypes that are "compatible" as far as `np.can_cast(np_in_datatype, np_datatype, 'safe')` is concerned, but aren't exact matches.  There's a schema feature that allows us to require an exact match on the datatype:

https://github.com/asdf-format/asdf-standard/blob/master/schemas/stsci.edu/asdf/asdf-schema-1.0.0.yaml#L41
